project:
  type: website
  output-dir: docs

website:
  title: "Robert Noel Prince"
  navbar:
    left:
      - research.qmd
      - about.qmd
    right: 
    - icon: file-text
      text: DMISRS
      href: https://robertprince.github.io/DMISRS/

format:
  html:
    backgroundcolor: "#eeffee"
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

