---
title: "Research"
about: # https://quarto.org/docs/websites/website-about.html/
  id: rprince-heading
  template: jolla
  links:
    - icon: envelope
      text: Email
      href: mailto:rprince@uj.ac.za
    - icon: file-text
      text: CV
      href: cv_rprince.pdf
    - icon: github
      text: Github
      href: https://github.com/robertprince
    - icon: google
      text: Scholar
      href: https://scholar.google.com/citations?user=NsGdESQAAAAJ&hl=en
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/feed/
    - icon: file-text
      text: DMISRS
      href: https://robertprince.github.io/DMISRS/
---

::: {#rprince-heading}
## Interests

-   Access to academic practices in higher education at undergraduate and postgraduate levels - ways of mediating the articulation gaps between the individual and group practices of students and the specific disciplinary practices encountered by them in higher education.

-   Educational testing in general and in particular the assessment of the Academic Literacies (Academic Literacy, Quantitative Literacy, Statistical Literacy, Mathematics, Scientific Reasoning, amongst others) of individuals and cohorts of students to assist with diagnosis of student learning difficulties, selection and placement of students into programmes, informing curriculum design and the provision of appropriate curricular interventions.

-   Teacher and tutor training practices in relation to academic literacies (including academic, quantitative, mathematical, scientific and statistical literacy): ways of mediating the multiple practices that teachers of academic literacies have to draw on to teach academic literacies.

-   The use of technology both as technical (psychometric and statistical) tools and as educational (blended learning) tools.

-   Commutative Algebra: Analogues of Number-Theory for Higher Dimensional Rings.

## Publications

**Journal articles published**

Prince, Robert N.. "Comparing National Benchmark Quantitative Literacy Paper-Based Tests Scores with its Computer-Based Counterparts." Numeracy 18, Iss. 1 (2025): Article 1. DOI: <https://doi.org/10.5038/1936-4660.18.1.1464>

Prince, R. N., & Simpson, Z. (2025). A Transformative Approach to Admissions Assessment: The South African Case. *Designs for Learning,* 16(1), 64–74. DOI: [https://doi.org/10.16993/dfl.232](https://zaf01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.16993%2Fdfl.232&data=05%7C02%7Crprince%40uj.ac.za%7C5fc04752af684aed0b9e08de0b487de1%7Cfa785acd36ef41bc8a9489841327e045%7C0%7C0%7C638960606332181150%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C60000%7C%7C%7C&sdata=fsmx4swUcgU3cFRxHS5%2BH%2FM8f5EpfG4%2BOoxk1tA9Vyc%3D&reserved=0 "Original URL: https://doi.org/10.16993/dfl.232. Click or tap if you trust this link.")

Prince, R. N., & Balarin, E. (2025). Reflecting on the Diagnostic Mathematics Information for Student Retention and Success (DMISRS) journey: Key insights into negotiating large-scale collaborative projects. *Perspectives in Education, 43*(4), 411-429. <https://doi.org/10.38140/pie.v43i4.9198>

Prince, R. N., & Simpson, Z. (2025). *Professional development of tertiary mathematics educators: A landscapes of practice approach.* *Perspectives in Education, 43*(4), 430-441. <https://doi.org/10.38140/pie.v43i4.8180>

Sango, T., Prince, R., Steyn, S., & Mudavanhu, P. 2022. High stakes online assessments: A case study of National Benchmark Tests during COVID-19. Perspectives in Education, 40(1), pp. 212-233.

Prince, R. N., Frith, V., Steyn, S. and Cliff, A. F. 2021. Academic and Quantitative Literacy in Higher Education: relationship with school-leaving subjects. South African Journal of Higher Education. 35, 3. pp 163 – 181.

Pienaar, L., Prince, R. and Abrahams, A. 2021. The Development of a Baseline Assessment tool to establish Students’ Foundational Knowledge of Life Sciences at entry into university. Journal of Health Professions Education. 13. pp 77-82.

Prince, R. and Frith, V. 2020. An investigation of the influence of mathematical competence and language ability on the academic numeracy of university students in South Africa. ZDM – Mathematics Education. 52, 433-445. DOI: https://doi.org/10.1007/s11858-019-01063-7

Simpson, Z. and Prince, R. 2018. Teaching, Learning, and Employing Analytical Frameworks as Performance: Analysis of a Quantitative Literacy Event in Applied Mechanics. Designs for Learning.10(1), 76-87. DOI: http://doi.org/10.16993/dfl.95

Frith, V. and Prince, R. 2018. The National Benchmark Quantitative Literacy Test for Applicants to South African Higher Education. Numeracy. 11 (2)

Prince, R. 2017. The relationship between school-leaving examinations and university entrance assessments: the case of the South African system. Journal of Education. 70. pp. 133 – 160.

Prince, R. and Frith, V. 2017. The quantitative literacy of South African school-leavers who qualify for higher education. Pythagoras. 38. (1) pp. 1 – 14.

Bohlmann, C., Prince, R. and Deacon, A. 2017. Mathematical Errors Made by High Performing Candidates Writing the National Benchmark Tests. Pythagoras. 38. pp. 1 – 10.

Prince, R. 2016. Predicting Success in Higher Education: The Value of Criterion and Norm-referenced Assessments. Practitioner Research in Higher education. 10, 1. pp. 22 – 38.

Frith, V. and Prince, R. 2016. Quantitative literacy of school leavers aspiring to higher education in South Africa: lessons from the National Benchmark Quantitative Literacy test. South African Journal of Higher Education. 30, 1. Pp. 138-161.

Prince, R. and Archer, A. 2014. Exploring Academic Voice in Multimodal Quantitative Texts. Literacy and numeracy Studies. 22, 1. pp. 39 - 58.

Kapp, R; Badenhorst, E; Bangeni, B; Craig, T. S; Janse van Rensburg, V; Le Roux, K, Prince, R; Pym, J; van Pletzen, E. 2014. Successful students’ negotiation of township schooling in contemporary South Africa. Perspectives in Education. 32, 3. pp. 50 - 61.

Frith, V. and Prince, R. 2009. A framework for understanding the quantitative literacy demands of higher education. South African Journal of Higher Education. 23, 1. 83 – 97. ISSN 1011-3487.

Prince, R. and Archer, A. 2008. A New Literacies approach to academic numeracy practices in Higher Education in South Africa. Literacy and Numeracy Studies. 16, 1. 63 – 75. ISSN 1441-0559.

Frith, V. and Prince, R.N. 2006. Reflections on the role of a research task for teacher education in data dandling in a Mathematical Literacy education course. Pythagoras 64. The Association for Mathematics Education of South Africa. pp. 52-61

Prince, R.N. and Archer, A. 2006. Quantitative Literacy as situated social practice in Higher Education. International Journal of Learning. 12. Common Ground Publishers. ISSN 1447-9494.

Frith, V, Prince, R.N. and Jaftha, J.J. 2004. Evaluating the Effectiveness of Interactive Computer Tutorials for an Undergraduate Mathematical literacy course. *British Journal of Educational Technology*, 35, 2, pp. 159-171

Archer, A., Frith, V, and Prince, R.N. 2002. A project-based approach to numeracy practices at university focusing on HIV/AIDS. *Literacy and Numeracy Studies*. 11, 2. pp. 123 -131. ISSN 1441-0559.

**Journal articles pending publication**

Komati, M, Prince, R. N and Korkie, E. (pending) The expected readiness of third year physiotherapy students in clinical education: Perspectives of academics in South Africa- South African Journal of Physiotherapy

Komati, M, Prince, R. N and Korkie, E. (pending) Setting Cut Scores for a Clinical Readiness Diagnostic Assessment for Third Year Physiotherapy Students- African Journal of Health Professions Education

Prince, Robert N. (pending). "Does the National Benchmark Quantitative Literacy Test Predict Performance in STEM Programmes in Commerce, Engineering and Science." Numeracy

**Journal articles under review**

Prince, R. N., Jappie, N., Millett, C. and Kefala, K. (under review) Beyond Selection Bias: What Propensity Score Matching Reveals About Extended Curriculum Programmes in South African Higher Education. Scholarship of Teaching and Learning in the South

Komati, M, Prince, R. N and Korkie, E. (under review) Validation of the Clinical Readiness Diagnostic Assessment (CRDA) for Third-Year Physiotherapy Students in South Africa: A Pilot Study- African Journal of Health Professions Education

Komati, M, Prince, R. N and Korkie, E. (under review) Development of a Clinical Readiness Diagnostic Assessment (CRDA) tool for third-year Physiotherapy students, in South Africa- Journal of Physiotherapy

Rzyankina, E, and Prince, R. N. (under review) Facilitating Epistemological Access to First-year Mathematics: The Case of a University of Technology. *Perspectives in Education*

**Publications in process**

Prince, R. (2025, November). Beyond Comparability: Materiality, Capital, and the Assessment of Academic Numeracy in a Digitally Divided Context.

Prince, R. (2025, November). Navigating the Engineering Pipeline: Quantitative Literacy as a Predictor of Success in a South African Context.

Prince, R. (2025, November). Extended versus Regular Curriculum Programmes in Engineering: A South African Case Study.

**Chapters in books**

Prince, R. N. and Simpson, Z (pending). Exploring the Influence of Socio-Economic Status on Higher Education Admissions Test Performance: A Large-Scale Quantitative Analysis.

Prince, R. 2022. Teaching, Learning and Assessment of Multimodal Digital Academic Numeracy Practices. In Maria Grazia Sindoni and Ilaria Moschini (Ed) Multimodal Literacies Across Digital Learning Contexts. pp. 247 - 259.

Kapp, R; Badenhorst, E; Bangeni, B; Craig, T. S; Janse van Rensburg, V; Le Roux, K, Prince, R; Pym, J; van Pletzen, E. 2017. Students’ negotiation of Learning and Identity in Working-class Schooling. In B. Bangeni and R. Kapp (Ed) Negotiating Learning and Identity in Higher Education: Access, Persistence and Retention. pp. 1 - 29.

Frith, V., Jaftha, J.J. and Prince, R.N. 2005. Interactive Excel Tutorials in a Quantitative Literacy Course for Humanities Students In: M.O. Thirunarayanan, Aixa Pérez-Prado (Eds.) *Integrating Technology in Higher Education*. University Press of America, Maryland. pp.247 - 258.

**Sections in books**

Frith, V. and Prince, R.N. 2006. Test domains and constructs: Quantitative literacy. In: H. Griesel (Ed) *Access and Entry Level Benchmarks, the National Benchmark Tests Project*, Higher Education South Africa -HESA, Pretoria. pp. 28-34.

Frith, V. and Prince, R.N. 2006. Elaboration on the elements of the definition of Quantitative Literacy. In: H. Griesel (Ed) *Access and Entry Level Benchmarks, the National Benchmark Tests Project*, Higher Education South Africa -HESA, Pretoria. pp. 47-54.

**Peer reviewed conference proceedings**

Prince R.N and Simpson, Z.S. 2025. Investigating the Relationship Between Mathematics and Retention and Success in Engineering Study: a South African Case Study. Proceedings of the European Society for Engineering Education (SEFI) Conference.

Prince R.N and Simpson, Z.S. 2024. Understanding the Support Mechanisms Available to First-Year

Mathematics Students: A Case Study from South Africa. Proceedings of the European Society for Engineering Education (SEFI) Conference.

Prince, R. and Simpson, Z. 2022. Does Higher Education Entrance Assessment in Academic Literacy Predict Success in Engineering Study? Proceedings of the IEEE ProComm (SEFI) Conference (IEEE ProComm 2022).

Prince, R., & Simpson, Z. (2021). Do Higher Education Entrance Exams Predict Success in Engineering Study?. In Heiß, H.-U., Järvinen, H.-M., Mayer, A., & Schulz, A. (Eds.), Blended Learning in Engineering Education: challenging, enlightening and lasting? SEFI 49th Annual Conference (pp. 420-428). European Society for Engineering Education (SEFI), Berlin, Germany. DOI: 10.5281/zenodo.14647050.

Prince, R. and Simpson, Z. 2021. Do Higher Education Entrance Exams Predict Success in Engineering Study? Proceedings of the 49th annual European Society of Engineering Education (SEFI) Conference (SEFI 2021). [https://www.sefi.be/wp-content/uploads/2021/12/SEFI49th-Proceedings-final.pdf](https://protect-za.mimecast.com/s/eliLCJZKmQtEP64mcG9P8i)

Prince, R., Mutakwa, D and Dunlop, J. 2019. The diagnostic potential of admissions tests for South African Higher education. Proceedings of the 8th Research in Engineering Education Symposium (REES 2019). https://www.sasee.org.za/wp-content/uploads/REES-2019-proceedings.pdf

Prince, R., Mutakwa, D and Dunlop, J. 2017. School-leaving and university entrance assessments in explaining performance in Engineering studies. Proceedings of the 4^th^ Biennial Conference of the South African Society for Engineering Education (SASEE). https://www.sasee.org.za/wp-content/uploads/Proceedings-of-the-4th-Biennial-SASEE-Conference-2017.pdf

Prince, R., and Bohlmann, C. 2016. Broadening Epistemological Access to Tertiary Mathematics: Challenges and Opportunities. Proceedings of the Southern Africa Mathematical Sciences Association (SAMSA2016). http://samsa-math.org/wp-content/uploads/2017/08/P1-20Princev2.pdf

Prince, R. and Simpson, Z. 2016. Quantitative Literacy Practices in Civil Engineering Study: Designs for Teaching and Learning. In Nortvig, A-M., Sørensen, B. H., Misfeldt, M., Ørngreen, R., Allsopp, B. B., Henningsen, B., & Hautopp, H. (Eds.). Proceedings of the 5th International Conference on Designs for Learning. (Open Access ed.) Aalborg Universitetsforlag.

Prince, R., and Frith, V. 2006. An approach to ‘Mathematical Literacy’ teacher education at a South African university. Proceedings of the Third International Conference on the Teaching of Mathematics (ICTM3). http://www.tmd.org.tr/sites/ICTM3/uploads/documents/ICTM3-2006.pdf

Frith, V., Jaftha, J.J. and Prince, R.N. 2004. Students' confidence in doing mathematics and in using computers in a university foundation course. In: A. Buffler and R.C. Laugksch (Eds.) Proceedings of the 12th Annual Conference of the Southern African Association for Research in Mathematics, Science and Technology Education. Durban: SAARMSTE.  pp. 234-245.

Archer, A., Frith, V and Prince, R.N. 2002. A project-based approach to numeracy practices at university focusing on HIV/AIDS. In *Proceedings of the Second International Conference on the Teaching of Mathematics (at the undergraduate level).* Creta Maris Hotel & Conference Centre, Greece 1- 6 July. John Wiley & Sons Inc. http://www.math.uoc.gr/\~ictm2/Proceedings/ICTM2_Proceedings_Table_of_Contents.html

ISBN 0-471-46332-9.

Frith, V., & Prince, R. N. (2001, July). *“Gatekeeper” vs “Gateway”*. In J. Engelbrecht (Ed.), *Proceedings of the Third Southern Hemisphere Symposium on Undergraduate Mathematics Teaching* (pp. 46–52). DELTA ’01: Warthog Conference, Kruger National Park, South Africa.
:::

## 
